name: FlutterCI
on: [push,pull_request]

jobs:
  check:
    name: Test on ${{ matrix.os }}
    #The type of machine to run the job on. [windows,macos, ubuntu , self-hosted]
    runs-on: macos-latest
    
    steps:
      - uses: actions/checkout@v1
      # Setup a flutter environment.
      # https://github.com/marketplace/actions/flutter-action
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '1.17.4'
          channel: 'stable'
      - run: cd flutter_model && flutter build ios-framework --cocoapods --output=../NativeDemo/Flutter 
